Develop
jellyocean/django-rest-auth pull request #1
Opened 2020-12-03 12:00 UTC by MutherPy

2020-12-03 12:38 UTC, jellyocean requested changes
Для проекта нужен README файл показывающий какие URL есть в пакете + перечисляющий настройки проекта

2020-12-03 12:38 UTC, jellyocean commented on django-prest-auth/README.rst
> +pREST API app
если что библиотека не позиционируется как prest дополнение, называться будет django-rest-jwt-auth

2020-12-03 12:38 UTC, jellyocean commented on django-prest-auth/django_rest_auth/views.py
> +            return HttpResponse('Data not correctly', status=HTTPStatus.BAD_REQUEST)
Здесь и далее возвращать надо JsonResponse (https://docs.djangoproject.com/en/3.1/ref/request-response/#jsonresponse-objects)

2020-12-03 12:38 UTC, jellyocean commented on django-prest-auth/django_rest_auth/views.py
> +def prest_signin(request):
просто signin. пакет уже итак называется django-rest-jwt-auth, так что дополнительно уточнять нет необходимости (с signup тоже самое)

2020-12-03 12:38 UTC, jellyocean commented on django-prest-auth/django_rest_auth/views.py
> +            return HttpResponse('Data not correctly', status=HTTPStatus.BAD_REQUEST)
Ошибка должна звучать как 

`Incorrect data format, JSON expected`

2020-12-03 12:38 UTC, jellyocean commented on django-prest-auth/django_rest_auth/views.py
> +def _create_jwt(user):
нижнее подчеркивание здесь не нужно (`_create_jwt` -> `create_jwt`)

2020-12-03 12:38 UTC, jellyocean commented on django-prest-auth/django_rest_auth/views.py
> +            return HttpResponse('', status=HTTPStatus.UNAUTHORIZED)
Статус должен быть 404

2020-12-03 12:38 UTC, jellyocean commented on django-prest-auth/django_rest_auth/views.py
> +            return HttpResponse('', status=HTTPStatus.UNAUTHORIZED)
Не надо возвращать пустой ответ. Потому что с пустым ответом статус должен быть 204. Тут надо возвращать JSON объект с ошибкой

2020-12-03 12:38 UTC, jellyocean commented on django-prest-auth/django_rest_auth/views.py
> +            return HttpResponse('Data not correctly', status=HTTPStatus.BAD_REQUEST)
Возвращаемый JSON объект должен содержать в себе поле `status` с статусом текущей операции

2020-12-03 12:38 UTC, jellyocean commented on django-prest-auth/django_rest_auth/urls.py
> +]
Надо добавить пустую линию в конце файла

2020-12-03 12:38 UTC, jellyocean commented on django-prest-auth/setup.cfg
> +packages = find:
Надо добавить пустую линию в конце файла

2020-12-03 12:38 UTC, jellyocean commented on docker-compose.yaml
> +version: "3"
Нужно убрать из репозитория

2020-12-03 12:38 UTC, jellyocean commented on django-prest-auth/setup.py
> +setup()
Нужно прописать установку зависимостей

2020-12-03 12:38 UTC, jellyocean commented on requirements.txt
> +psycopg2-binary>=2.8.6
это здесь не нужно, нужно проставить зависимость от django.

2020-12-03 12:38 UTC, jellyocean commented on requirements.txt
>  pytz==2020.4
Для чего здесь `pytz` и `sqlparse`?

2020-12-03 12:38 UTC, jellyocean commented on restauth/restauth/settings.py
Этот пакет надо убрать из репозитория (`restauth`)

2020-12-03 12:47 UTC, MutherPy commented on django-prest-auth/README.rst
> +pREST API app
Но ведь она же не будет работать не с престом

2020-12-03 12:48 UTC, MutherPy commented on django-prest-auth/django_rest_auth/views.py
> +            return HttpResponse('Data not correctly', status=HTTPStatus.BAD_REQUEST)
хорошо

2020-12-03 12:48 UTC, MutherPy commented on django-prest-auth/django_rest_auth/views.py
> +def prest_signin(request):
хорошо

2020-12-03 12:48 UTC, MutherPy commented on django-prest-auth/django_rest_auth/views.py
> +def _create_jwt(user):
я подумал, что не стоит его использовать извне, и что бы показать это

2020-12-03 12:49 UTC, MutherPy commented on django-prest-auth/django_rest_auth/views.py
> +            return HttpResponse('', status=HTTPStatus.UNAUTHORIZED)
Почему статус 404, у нас же не найдет юзер, потому что он не смог авторизоваться

2020-12-03 12:49 UTC, MutherPy commented on django-prest-auth/django_rest_auth/views.py
> +            return HttpResponse('', status=HTTPStatus.UNAUTHORIZED)
джисон, понял

2020-12-03 12:50 UTC, jellyocean commented on django-prest-auth/README.rst
> +pREST API app
почему ты так думаешь?

2020-12-03 12:51 UTC, jellyocean commented on django-prest-auth/django_rest_auth/views.py
> +def _create_jwt(user):
почему не стоит его использовать извне?

2020-12-03 12:52 UTC, jellyocean commented on django-prest-auth/django_rest_auth/views.py
> +            return HttpResponse('', status=HTTPStatus.UNAUTHORIZED)
> Почему статус 404, у нас же не найдет юзер, потому что он не смог авторизоваться

Потому что юзер не найден. 

401 статус высылается когда неавторизаваный пользователь пытается зайти на страницу на которую ему нельзя, и тогда сервер дает знать что юзер не авторизован для этой операции

2020-12-03 12:54 UTC, MutherPy commented on django-prest-auth/README.rst
> +pREST API app
ммм...так показалось

2020-12-03 12:55 UTC, MutherPy commented on django-prest-auth/django_rest_auth/views.py
> +def _create_jwt(user):
ну...типо это получается как сервис, для получения доступа, и мне кажется, что не стоит его функционал выносить, просто а где оно может понадобиться ведь..?

2020-12-10 12:18 UTC, jellyocean requested changes

2020-12-10 12:18 UTC, jellyocean commented on django_rest_jwt_auth/views.py
> +        'userid': str(user.id),
а чего тут все еще `id` юзера?

2020-12-10 12:18 UTC, jellyocean commented on django_rest_jwt_auth/views.py
> +    fernet_encr = Fernet(settings.EMAIL_ENCRYPT_KEY)
А почему используется ключ для емейлов? Нужен отдельный ключ для токена

2020-12-10 12:18 UTC, jellyocean commented on django_rest_jwt_auth/views.py
> +@csrf_exempt
Я помню что мы это обсуждали и пришли к другому выводу но сейчас я понял что насильно блокировать CSRF не очень правильно, это надо будет убрать, пусть пользователь сам решает, нужен ему CSRF или нет, его всегда можно выключить в настройках

2020-12-10 12:18 UTC, jellyocean commented on django_rest_jwt_auth/views.py
> +def get_error(code):
Я понимаю что ты тут пытался сделать, но этот подход не совсем идеальный потому что человеку который читает код придется каждый раз прыгать к этой функции что бы понять что отправляется. Аббревиатуры - неплохой вариант, но тем не менее они не очевидные, и запомнить их сходу не выходит. 

Питон поддерживает перечисления, лучше использовать их. Нечто вроде 

```python
class ErrorCode(Enum):
    WRONG_DATA_FORMAT = 'Incorrect data format, JSON expected'
    ...
```
или можно отдельный файл сделать с константами
сейчас придется пописать больше но потом сэкономит время

2020-12-10 12:18 UTC, jellyocean commented on django_rest_jwt_auth/views.py
> +        restoring_email = restoring_data.get('restoring_email')
Поля лучше назвать просто `email`, `password` и `token`

2020-12-10 12:21 UTC, MutherPy commented on django_rest_jwt_auth/views.py
> +        'userid': str(user.id),
так это для преста еще

2020-12-10 12:22 UTC, MutherPy commented on django_rest_jwt_auth/views.py
> +    fernet_encr = Fernet(settings.EMAIL_ENCRYPT_KEY)
ну это же отдельный ключ для токена, который с эмейлом передается

2020-12-10 12:22 UTC, MutherPy commented on django_rest_jwt_auth/views.py
> +    fernet_encr = Fernet(settings.EMAIL_ENCRYPT_KEY)
просто называется так, потому что он как бы с емейлом идет в паре

2020-12-10 12:23 UTC, MutherPy commented on django_rest_jwt_auth/views.py
> +@csrf_exempt
хорошо, то есть убрать везде декораторы, но если он не захочет убирать его полностью. в настройках же, ты имеешь ввиду убрать мидлваре?

2020-12-10 12:25 UTC, MutherPy commented on django_rest_jwt_auth/views.py
> +def get_error(code):
хорошо, подумаю

2020-12-10 12:25 UTC, MutherPy commented on django_rest_jwt_auth/views.py
> +        restoring_email = restoring_data.get('restoring_email')
это для наглядности

2020-12-10 12:35 UTC, MutherPy commented on django_rest_jwt_auth/views.py
> +def get_error(code):
может я просто расширю названия? полностью их писать. можно в принципе и в отдельном файлике, но насколько это мб выгодно?

2020-12-10 12:43 UTC, jellyocean commented on django-prest-auth/django_rest_auth/views.py
> +def _create_jwt(user):
ну мы не можем предполагать что он нигде извне не понадобится, в плане секьюрности тут проблем не будет, он все равно сможет использоваться только в рамках проекта

2020-12-10 12:44 UTC, jellyocean commented on django_rest_jwt_auth/views.py
> +        'userid': str(user.id),
ок

2020-12-10 12:45 UTC, jellyocean commented on django_rest_jwt_auth/views.py
> +@csrf_exempt
да, если все таки понадобится выключить CSRF можно в настройках проекта

2020-12-10 12:46 UTC, jellyocean commented on django_rest_jwt_auth/views.py
> +def get_error(code):
Тут дело еще не только в этом а в том что IDE может показать значение константы без перехода к самой константе, а в случае с функцией придется переходить на нее каждый раз

2020-12-10 12:47 UTC, jellyocean commented on django_rest_jwt_auth/views.py
> +        restoring_email = restoring_data.get('restoring_email')
я понимаю, но если ты шлешь данные на url `restore` ты уже понимаешь для чего ты это делаешь

2020-12-18 15:54 UTC, jellyfish-tech approved these changes

2020-12-18 15:54 UTC, merged